import { readRssFeeds } from './rss'

export type EnvironmentalSourceType = 'measurement' | 'official-api' | 'rss' | 'news' | 'cache'
export type EnvironmentalStatus = 'available' | 'unavailable' | 'stale' | 'error'
export type WaterLocation = 'schlei' | 'yamuna'
export type WaterMetric = 'ph' | 'clarity' | 'microplastics'
export type EnvironmentalReading = { id: string; location: WaterLocation; label: string; value: string | null; unit: string | null; source: string; sourceUrl: string | null; sourceType: EnvironmentalSourceType; status: EnvironmentalStatus; fetchedAt: string | null; publishedAt: string | null; note: string }
export type EnvironmentalSnapshot = { checkedAt: string; readings: EnvironmentalReading[]; feeds: { name: string; sourceType: EnvironmentalSourceType; status: EnvironmentalStatus; lastChecked: string; detail: string }[]; updates: { id: string; title: string; link: string; source: string; publishedAt: string | null; sourceType: 'rss'; description: string | null }[] }

type SourcePayload = Partial<Record<WaterMetric, { value: number; unit: string; measuredAt?: string; sourceUrl?: string }>>
const locations = [
  { key: 'schlei' as const, label: 'Schlei fjord', endpoint: process.env.SCHLEI_WATER_API_URL, source: 'Schleswig-Holstein official water monitoring', sourceUrl: 'https://umweltgeodienste.schleswig-holstein.de/WFS_UWAT' },
  { key: 'yamuna' as const, label: 'Yamuna', endpoint: process.env.YAMUNA_WATER_API_URL, source: 'CPCB official water monitoring', sourceUrl: 'https://cpcb.nic.in/nwmp-data-2023/' },
]
const metricMeta: Record<WaterMetric, { label: string; unit: string }> = { ph: { label: 'pH level', unit: 'pH' }, clarity: { label: 'Clarity / turbidity', unit: 'NTU' }, microplastics: { label: 'Microplastics', unit: 'items/L' } }
function unavailable(location: WaterLocation, label: string, source: string, note: string, sourceUrl: string | null = null): EnvironmentalReading[] { return (Object.entries(metricMeta) as [WaterMetric, { label: string; unit: string }][]).map(([metric, meta]) => ({ id: `${location}-${metric}`, location, label: `${label} · ${meta.label}`, value: null, unit: null, source, sourceUrl, sourceType: 'official-api', status: 'unavailable', fetchedAt: null, publishedAt: null, note })) }
function parsePayload(value: unknown): SourcePayload | null { if (!value || typeof value !== 'object') return null; const root = value as Record<string, unknown>; const candidate = (root.data && typeof root.data === 'object' ? root.data : root) as Record<string, unknown>; const output: SourcePayload = {}; for (const metric of Object.keys(metricMeta) as WaterMetric[]) { const raw = candidate[metric] ?? candidate[metric === 'ph' ? 'pH' : metric === 'clarity' ? 'turbidity' : metric]; const number = typeof raw === 'number' ? raw : typeof raw === 'string' && raw.trim() ? Number(raw) : NaN; if (Number.isFinite(number)) output[metric] = { value: number, unit: metricMeta[metric].unit, measuredAt: typeof candidate.measuredAt === 'string' ? candidate.measuredAt : undefined, sourceUrl: typeof candidate.sourceUrl === 'string' ? candidate.sourceUrl : undefined } } return Object.keys(output).length ? output : null }
async function readLocation(location: typeof locations[number], checkedAt: string) { if (!location.endpoint) return { readings: unavailable(location.key, location.label, location.source, 'No official endpoint configured for this location.', location.sourceUrl), feed: { name: `${location.label} official API`, sourceType: 'official-api' as const, status: 'unavailable' as const, lastChecked: checkedAt, detail: 'Set the server-only endpoint URL to enable verified readings.' } }; const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 8000); try { const response = await fetch(location.endpoint, { signal: controller.signal, headers: { Accept: 'application/json' }, next: { revalidate: 900 } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); if (!(response.headers.get('content-type') ?? '').includes('json')) throw new Error('Official endpoint did not return JSON'); const payload = parsePayload(await response.json()); if (!payload) throw new Error('No supported measurements in official response'); const readings = (Object.entries(metricMeta) as [WaterMetric, { label: string; unit: string }][]).map(([metric, meta]) => { const item = payload[metric]; return { id: `${location.key}-${metric}`, location: location.key, label: `${location.label} · ${meta.label}`, value: item ? String(item.value) : null, unit: item?.unit ?? null, source: location.source, sourceUrl: item?.sourceUrl ?? location.endpoint!, sourceType: 'official-api' as const, status: item ? 'available' as const : 'unavailable' as const, fetchedAt: checkedAt, publishedAt: item?.measuredAt ?? null, note: item ? 'Verified official measurement.' : 'This official source did not report this metric.' } }); return { readings, feed: { name: `${location.label} official API`, sourceType: 'official-api' as const, status: 'available' as const, lastChecked: checkedAt, detail: 'Official response received and normalized.' } } } catch (error) { const detail = error instanceof DOMException && error.name === 'AbortError' ? 'Official endpoint timed out.' : error instanceof Error ? error.message : 'Official endpoint failed.'; return { readings: unavailable(location.key, location.label, location.source, `Measurement unavailable: ${detail}`, location.endpoint), feed: { name: `${location.label} official API`, sourceType: 'official-api' as const, status: 'error' as const, lastChecked: checkedAt, detail } } } finally { clearTimeout(timeout) } }
export async function getEnvironmentalSnapshot(): Promise<EnvironmentalSnapshot> { const checkedAt = new Date().toISOString(); const [rss, ...locationResults] = await Promise.all([readRssFeeds(), ...locations.map((location) => readLocation(location, checkedAt))]); return { checkedAt, readings: locationResults.flatMap((result) => result.readings), feeds: [...locationResults.map((result) => result.feed), ...rss.feeds.map(({ name, status, lastChecked, detail }) => ({ name, sourceType: 'rss' as const, status, lastChecked, detail }))], updates: rss.updates } }
