import { readRssFeeds } from './rss'

export type EnvironmentalSourceType = 'measurement' | 'official-api' | 'rss' | 'news' | 'cache'
export type EnvironmentalStatus = 'available' | 'unavailable' | 'stale' | 'error'
export type WaterLocation = 'schlei' | 'yamuna'
export type WaterMetric = 'ph' | 'clarity' | 'microplastics'
export type EnvironmentalReading = { id: string; location: WaterLocation; label: string; value: string | null; unit: string | null; source: string; sourceUrl: string | null; sourceType: EnvironmentalSourceType; status: EnvironmentalStatus; fetchedAt: string | null; publishedAt: string | null; note: string }
export type EnvironmentalSnapshot = { checkedAt: string; readings: EnvironmentalReading[]; feeds: { name: string; sourceType: EnvironmentalSourceType; status: EnvironmentalStatus; lastChecked: string; detail: string }[]; updates: { id: string; title: string; link: string; source: string; publishedAt: string | null; sourceType: 'rss'; description: string | null }[] }

type SourcePayload = Partial<Record<WaterMetric, { value: number; unit: string; measuredAt?: string }>>
type LocationConfig = { key: WaterLocation; label: string; endpoint?: string; source: string; sourceUrl: string }
const locations: LocationConfig[] = [
  { key: 'schlei', label: 'Schlei fjord', endpoint: process.env.SCHLEI_WATER_API_URL, source: 'Schleswig-Holstein official water monitoring', sourceUrl: 'https://umweltgeodienste.schleswig-holstein.de/WFS_UWAT' },
  { key: 'yamuna', label: 'Yamuna', endpoint: process.env.YAMUNA_WATER_API_URL, source: 'CPCB official water monitoring', sourceUrl: 'https://cpcb.nic.in/nwmp-data-2023/' },
]
const metricMeta: Record<WaterMetric, { label: string; unit: string }> = { ph: { label: 'pH level', unit: 'pH' }, clarity: { label: 'Clarity / turbidity', unit: 'NTU' }, microplastics: { label: 'Microplastics', unit: 'items/L' } }
const metricKeys: WaterMetric[] = ['ph', 'clarity', 'microplastics']

function readingsFor(location: LocationConfig, status: EnvironmentalStatus, note: string, values: SourcePayload = {}, checkedAt: string | null = null): EnvironmentalReading[] {
  return metricKeys.map((metric) => { const meta = metricMeta[metric]; const item = values[metric]; return { id: `${location.key}-${metric}`, location: location.key, label: `${location.label} · ${meta.label}`, value: item ? String(item.value) : null, unit: item?.unit ?? null, source: location.source, sourceUrl: location.sourceUrl, sourceType: 'official-api', status: item ? status : 'unavailable', fetchedAt: checkedAt, publishedAt: item?.measuredAt ?? null, note: item ? note : metric === 'microplastics' ? 'No official microplastics measurement is published by this source.' : 'No verified measurement is available from this source.' } })
}
function parsePayload(value: unknown): SourcePayload | null { if (!value || typeof value !== 'object') return null; const root = value as Record<string, unknown>; const candidate = root.data && typeof root.data === 'object' ? root.data as Record<string, unknown> : root; const output: SourcePayload = {}; for (const metric of metricKeys) { const raw = candidate[metric] ?? candidate[metric === 'ph' ? 'pH' : metric === 'clarity' ? 'turbidity' : 'microplastics']; const number = typeof raw === 'number' ? raw : typeof raw === 'string' && raw.trim() ? Number(raw) : NaN; if (!Number.isFinite(number)) continue; const measuredAt = typeof candidate.measuredAt === 'string' && !Number.isNaN(Date.parse(candidate.measuredAt)) ? new Date(candidate.measuredAt).toISOString() : undefined; output[metric] = { value: number, unit: metricMeta[metric].unit, measuredAt } } return Object.keys(output).length ? output : null }
async function readLocation(location: LocationConfig, checkedAt: string) { if (!location.endpoint) return { readings: readingsFor(location, 'unavailable', 'This official source is not connected yet.'), feed: { name: `${location.label} official API`, sourceType: 'official-api' as const, status: 'unavailable' as const, lastChecked: checkedAt, detail: 'No server-side official endpoint is configured; no value is shown.' } }; const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 8000); try { const response = await fetch(location.endpoint, { signal: controller.signal, headers: { Accept: 'application/json' }, cache: 'no-store' }); if (!response.ok) throw new Error(`HTTP ${response.status}`); if (!(response.headers.get('content-type') ?? '').toLowerCase().includes('json')) throw new Error('Official endpoint did not return JSON'); const payload = parsePayload(await response.json()); if (!payload) throw new Error('No supported measurements in official response'); return { readings: readingsFor(location, 'available', 'Verified official measurement.', payload, checkedAt), feed: { name: `${location.label} official API`, sourceType: 'official-api' as const, status: 'available' as const, lastChecked: checkedAt, detail: 'Official response received and normalized.' } } } catch (error) { return { readings: readingsFor(location, 'error', 'The official source could not be read; no value is shown.'), feed: { name: `${location.label} official API`, sourceType: 'official-api' as const, status: 'error' as const, lastChecked: checkedAt, detail: error instanceof Error ? error.message : 'Official source could not be read.' } } } finally { clearTimeout(timeout) } }
export async function getEnvironmentalSnapshot(): Promise<EnvironmentalSnapshot> { const checkedAt = new Date().toISOString(); const [rss, ...locationResults] = await Promise.all([readRssFeeds(), ...locations.map((location) => readLocation(location, checkedAt))]); return { checkedAt, readings: locationResults.flatMap((result) => result.readings), feeds: [...locationResults.map((result) => result.feed), ...rss.feeds.map(({ name, status, lastChecked, detail }) => ({ name, sourceType: 'rss' as const, status, lastChecked, detail }))], updates: rss.updates } }
